spring:
  application:
    name: mybooking
  datasource:
    url: jdbc:postgresql://localhost:5432/mybooking
    username: ${DB_USER:mybooking}
    password: ${DB_PASS:mybooking}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
